#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
# To avoid jffs2 ECC errors:
#echo 1 > /proc/sys/kernel/printk
#modprobe u_serial
#modprobe g_serial
modprobe g_multi file=/file
/usr/bin/setfont
if [ -x /etc/run_once.sh ] ; then /etc/run_once.sh ; fi
date '2024-10-30 21:00:00'

for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
        *.sh)
            # Source shell script for speed.
            (
                trap - INT QUIT TSTP
                set start
                . $i
            )
            ;;
        *)
            # No sh extension, so fork subprocess.
            $i start
            ;;
    esac
done
